### ISSUE TITLE
Support custom-level of blocks as "confirmations" in ForkableHandler

### ISSUE THREAD

**Issue by abourget** [dfuse-io/bstream#4]
This would allow people to search for things, but not be informed of them before _x blocks deep_.

Useful for ETH world, where there's no finality.  Perhaps people on EOSIO would also prefer faster responses, without waiting for 300 blocks with a fully disperse production schedule.

**Comment by sduchesneau** [comment]
Closing old feature request: ETH now has finality, no one is asking for this at the moment...
